apps/clinica/urls.py
from django.conf.urls import url


from .views.atencionviews import AtencionHistoriaListView, AtencionListView, AtencionCreateView, AtencionTerminadaView
from .views.colamedicaviews import ColaMedicaListView,MainCreateView, ColaMedicaDeleteView, ColasMedicasListView, BuscarCliente
from .views.vacunacionviews import  get_drugs, BuscarProducto
from .views.consulta_diagnostico import  get_diagnosticos
from .views.tratamientos import  get_tratamientos
from .views.consulta_pruebas_auxiliares import  get_pruebas_auxiliares
from .views.historiaviews import HistoriasListView, HistoriaFichaListView,  HistoriaMascotaDetailView, HistoriaMascotaCreateView
from .views.mascotaviews import MascotaListView, MascotaCreateView, MascotaPerfilView, MascotaHistoriaListView, MascotaUpdateView, MascotaUpdateActiveView
from .views.cliente import ClienteListView, ClienteCreateView, ClienteUpdateView, ClienteDeleteView, PostClienteAjax
from .views.cunsulta import ConsultaCreateView, ConsultaUpdateView,  ConsultaDeleteView
from .views.notas import NotasCreateView, upload, upload_delete
from .views.vacunacion import VacunacionCreateView, PostVacunacionAjax
from .views.colamedicaviews import MainCreateView,VentasView
urlpatterns = [
    url(r'^api/get_drugs/', get_drugs, name='get_drugs'),
    url(r'^api/diagnostico/', get_diagnosticos, name='get_diagnosticos'),
    url(r'^api/pruebas_auxiliares/', get_pruebas_auxiliares, name='get_pruebas_auxiliares'),
    url(r'^api/tratamientos/', get_tratamientos, name='get_tratamientos'),

    #BUSQUEDAS-URLS

    url(r'^producto/search/',
        BuscarProducto, name='search_producto_recepcion'),
    url(r'^cliente/search/',BuscarCliente, name='search_cliente'),



#Atencion Medica
    url(r'^atenciones/listar/(?P<mascota_pk>[^/]+)/(?P<colamedica_pk>[^/]+)$', AtencionListView.as_view(), name="historia_list"),
    url(r'^atenciones/historia/(?P<mascota_pk>[^/]+)/(?P<colamedica_pk>[^/]+)$', AtencionHistoriaListView.as_view(), name="atencion_historia_list"),
    url(r'^atenciones/crear/(?P<mascota_pk>[^/]+)/(?P<colamedica_pk>[^/]+)/$', AtencionCreateView.as_view(), name="atenciones_add"),
    url(r'^atencion/terminada/(?P<state>[\w\d\-]+)/(?P<pk>.*)/$',
        AtencionTerminadaView.as_view(), name='atencion_satate'),

#Consultas
    url(r'^atencion/consulta/(?P<mascota_pk>[^/]+)/(?P<colamedica_pk>[^/]+)$', ConsultaCreateView.as_view(), name='consulta_add'),
    url(r'^atencion/consulta/editar/(?P<mascota_pk>[^/]+)/(?P<colamedica_pk>[^/]+)/(?P<atencion_pk>[^/]+)/(?P<pk>.*)/$', ConsultaUpdateView.as_view(), name='consulta_update'),
    url(r'^atencion/consulta/eliminar/(?P<mascota_pk>[^/]+)/(?P<colamedica_pk>[^/]+)/(?P<pk>.*)/$', ConsultaDeleteView.as_view(), name="consulta_delete"),

    #Notas
    url(r'^atencion/notas/(?P<mascota_pk>[^/]+)/(?P<colamedica_pk>[^/]+)/(?P<atencion_pk>[^/]+)/$', NotasCreateView.as_view(), name='nota_add'),

    #Archivos

    #Vacunacion
    url(r'^atencion/vacunacion/(?P<mascota_pk>[^/]+)/(?P<colamedica_pk>[^/]+)/$', VacunacionCreateView.as_view(), name='vacuna_add'),
    url(r'^atencion/vacunacion/crear-ajax/$', PostVacunacionAjax, name="post_vacunacion_ajax"),

    #Cola Medica
    url(r'^colamedica/listar/$', ColaMedicaListView.as_view(), name="listar_medica"),
    url(r'^colamedica/lista/$', ColasMedicasListView.as_view(), name="lista_medica"),

    url(r'^colamedica/crear/$', MainCreateView.as_view(), name="crear_medica"),
    url(r'^ventas/$', VentasView.as_view(), name="crear_venta"),
    url(r'^colamedica/eliminar/(?P<pk>.*)/$', ColaMedicaDeleteView.as_view(), name="eliminar_medica"),

    #url(r'^colamedica/detail/(?P<pk>.*)/$', AtencionMedicaView.as_view(), name='colamedica_detail'),



    # Historia
    url(r'^historia/listar/$', HistoriasListView.as_view(), name="listar_historia"),
    url(r'^historia/ficha/(?P<mascota_pk>[^/]+)$', HistoriaFichaListView.as_view(), name="ver_ficha_clinica"),
    url(r'^historia/crear/(?P<cliente_pk>[^/]+)/(?P<mascota_pk>[^/]+)$',
        HistoriaMascotaCreateView.as_view(), name='crear_historia'),
    url(r'^historia/detail/(?P<pk>.*)/$',
        HistoriaMascotaDetailView.as_view(), name='historia_detail'),

    # Mascota
    url(r'^mascota/listar/(?P<cliente_pk>[^/]+)$',
        MascotaListView.as_view(), name="mascota_list"),
    url(r'^mascota/crear/(?P<cliente_pk>[^/]+)$',
        MascotaCreateView.as_view(), name="mascota_add"),
    url(r'^mascota/actualizar/(?P<pk>.*)/$',
        MascotaUpdateView.as_view(), name="actualizar_mascota"),
    url(r'^mascota/state/(?P<state>[\w\d\-]+)/(?P<pk>.*)/$',
        MascotaUpdateActiveView.as_view(), name='mascota-state'),
    url(r'^mascota/perfil/(?P<pk>.*)/$', MascotaPerfilView.as_view(), name="mascota_perfil_list"),
    url(r'^mascota/historia/(?P<mascota_pk>[^/]+)/$', MascotaHistoriaListView.as_view(), name="historia_list"),
    # ===================CLIENTE==========================
    url(r'^cliente/listar/$', ClienteListView.as_view(), name="cliente_list"),
    url(r'^cliente/crear/$', ClienteCreateView.as_view(), name="cliente_add"),
    url(r'^cliente/actualizar/(?P<pk>.*)/$',
        ClienteUpdateView.as_view(), name="cliente_upd"),
    url(r'^cliente/eliminar/(?P<pk>.*)/$',
        ClienteDeleteView.as_view(), name="cliente_del"),
    url(r'^cliente/crear/ajax$', PostClienteAjax, name="post_cliente_ajax"),
]

config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django import views as django_views

from apps.clinica.views.notas import upload, upload_delete

from apps.clivet.views.main import  MainView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/', django_views.i18n.javascript_catalog),
    # =============================================================
    #                           backengo
    # =============================================================
    url(r'^mod_backend/', include('apps.mod_backend.urls', namespace='mod_backend')),
    url(r'^space/', include('apps.space.urls', namespace='space')),
    url(r'^sad/', include('apps.sad.urls', namespace='sad')),
    url(r'^accounts/', include('apps.accounts.urls')),
    # =============================================================
    #                           clivet
    # =============================================================


    url( r'upload/', upload, name = 'jfu_upload' ),
    url( r'^delete/(?P<pk>\d+)$', upload_delete, name = 'jfu_delete' ),

    # url(r'^about/$', AboutView.as_view()),
    url(r'^$', MainView.as_view(), name='dashboard'),

    url(r'^', include('apps.clivet.urls', namespace='clivet')),
    url(r'^clinica/', include('apps.clinica.urls', namespace='clinica')),
    url(r'^ventas/', include('apps.ventas.urls', namespace='ventas')),
    url(r'^configuracion/', include('apps.configuracion.urls', namespace='configuracion')),
    url(r'^compras/', include('apps.compras.urls', namespace='compras')),
    url(r'^citas/', include('apps.citas.urls', namespace='citas')),
    url(r'^acopios/', include('apps.acopios.urls', namespace='acopios')),
    # TODO: Poner en la aplicacion que se usa
    url(r'^chaining/', include('smart_selects.urls')),
]

urlpatterns = urlpatterns + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

apps/clinica/models/consulta.py
# coding: utf-8 _*_
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.text import capfirst
from django.dispatch import receiver
from django.db.models import signals
from unicodedata import normalize
from django.core.exceptions import ValidationError

from apps.clinica.models.mascota import Mascota
# Create your models here.

class Diagnostico(models.Model):
    nombre = models.CharField(max_length=20)
    def __str__(self):
        return "%s" % (self.nombre)
class HallasgosClinicos(models.Model):
    nombre = models.CharField(max_length=20)
    def __str__(self):
        return "%s" % (self.nombre)
class Pruebas(models.Model):
    nombre = models.CharField(max_length=20)
    def __str__(self):
        return "%s" % (self.nombre)
class Tratamiento(models.Model):
    nombre = models.CharField(max_length=20)
    def __str__(self):
        return "%s" % (self.nombre)

apps/clinica/models/historia.py
# coding: utf-8 _*_
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.text import capfirst
from django.dispatch import receiver
from django.db.models import signals
from unicodedata import normalize
from django.core.exceptions import ValidationError

from apps.sad.models import User
from apps.clinica.models.mascota import Mascota

CARACTER = (
    ('tranquilo', "Tranquilo"),
    ('agresivo', "Agresivo"),
    ('nervioso', "Nervioso")
)

ACTIVIDAD = (
    ('alta', "Alta"),
    ('normal', "Normal"),
    ('baja', "Baja")
)

HABITAT = (
    ('casa', "Casa"),
    ('azotea', "Azotea"),
    ('campo', "Campo"),
    ('patio', "Patio"),
    ('criadero', "Criadero"),
    ('jardin', "Jardin"),
    ('calle', "Calle")
)

ALIMENTACION = (
    ('balanceada', "Balanceada seca"),
    ('lata', "Lata"),
    ('casera', "Casera"),
    ('huevos', "Huevos"),
    ('huevos', "Otros")
)

APTITUP = (
    ('compañia', "Compañia"),
    ('guardia', "Guardia"),
    ('trabajo', "Trabajo"),
    ('deporte', "Deporte"),
    ('casa', "Casa")
)

CONVIVE = (
    ('Si', "Sí"),
    ('No', "No")
)

# Create your models here.

class Historial(models.Model):
    num_historia = models.CharField(max_length=40, unique=True)
    veterinario = models.ForeignKey(User)
    mascota = models.ForeignKey(Mascota, verbose_name=_('Mascota'), null=True, blank=True,)
    created_ath = models.DateTimeField(_('Fecha Creada'), auto_now_add=True)
#reseña de la amscota
    caracter = models.CharField(max_length=100, choices=CARACTER ,null=True, blank=True)
    actividad = models.CharField(max_length=100, choices=ACTIVIDAD ,null=True, blank=True)
    habitar = models.CharField(max_length=100, choices=HABITAT ,null=True, blank=True)
    alimentacion = models.CharField(max_length=100, choices=ALIMENTACION , null=True, blank=True)
    aptitup = models.CharField(max_length=100, choices=APTITUP ,null=True, blank=True)
    convive = models.CharField(max_length=100, choices=CONVIVE ,null=True, blank=True)

    class Meta:
        verbose_name = "Historia"
        verbose_name_plural = "Historias"
        permissions = (
            ('historia', 'Can ALL historia'),
        )
    def _num(self):
        return "%s" % (self.id)

    def __str__(self):
        return "%s %s %s %s" % ("La mascota", self.mascota, "con N° Historia", self.num_historia)

apps/clinica/models/mascota.py
# coding: utf-8 _*_
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.text import capfirst
from django.dispatch import receiver
from django.db.models import signals
from unicodedata import normalize
from django.core.exceptions import ValidationError

from smart_selects.db_fields import ChainedForeignKey

from ..models.cliente import Cliente
from apps.configuracion.models.especie import Especie, Raza, Color

CONDICION = (
    ('Buena', "Buena"),
    ('Regular', "Regular"),
    ('Demacrada', "Demacrada")
)

BOOL_GENERO = (
    ('Macho', "Macho"),
    ('Hembra', "Hembra")
)


class Mascota(models.Model):

    nombre = models.CharField(max_length=100)
    duenho = models.ForeignKey(Cliente, related_name='mascotas')
    fecha_nacimiento = models.DateTimeField(
        capfirst(_('Fecha Nacimiento')), null=True, blank=True)
    genero = models.CharField(
        max_length=10, choices=BOOL_GENERO, default='Macho')
    especie = models.ForeignKey(Especie, related_name='especie', max_length=100)
    raza = ChainedForeignKey(
		Raza,
		chained_field="especie",
		chained_model_field="especie",
		show_all=False,
		auto_choose=True,
        sort=True
	)
    color = ChainedForeignKey(
    	Color,
    	chained_field="raza",
    	chained_model_field="raza",
    	show_all=False,
    	auto_choose=True,
        sort=True
    )
    cond_corporal = models.CharField(
        max_length=10, choices=CONDICION, default='Buena')
    esterelizado = models.BooleanField(
        capfirst(_('Esterelizado...?')), default=True)
    is_active = models.BooleanField(capfirst(_('active')), default=True)
    is_actived = models.BooleanField(_('Actived'), default=False)
    descripcion = models.CharField(max_length=200)

    class Meta:
        verbose_name = "Mascota"
        verbose_name_plural = "Mascotas"
        permissions = (
            ('mascota', 'Can ALL mascota'),
            ('mascota_perfil', 'Can LIST perfil'),
        )

    def __str__(self):
        return "%s" % self.nombre

apps/acopios/forms/acopio.py
from django import forms
from ..models.acopio import Acopio
from apps.params.models import IDENTITY_TYPE_CHOICES


class AcopioForm(forms.ModelForm):
    u"""Tipo Documeto Form."""

    producto = forms.CharField(label="", required=False,
                               widget=forms.TextInput(attrs={'type': 'search', 'class': 'form-control typeahead input-lg', 'placeholder': 'Buscar Producto ', 'autofocus': 'autofocus'}))
    data_compra = forms.CharField(
        required=False, widget=forms.TextInput(attrs={'type': 'hidden'}))

    # =====================modal==========================
    tipo_doc = forms.ChoiceField(
        choices=IDENTITY_TYPE_CHOICES, required=False,
        label='Tipo de documento')

    class Meta:

        model = Acopio
        fields = ('total', 'socio', 'n_ticket')
        exclude = ()
        widgets = {
            'socio': forms.Select(
                attrs={'class': 'chosen-select',
                       'data-placeholder': 'Choose a Country', 'style': 'width: 100%;height:34px;'}),
            'total': forms.TextInput(attrs={'class': 'form-control text-left'}),
            'n_ticket': forms.ClearableFileInput()}

    def __init__(self, *args, **kwargs):
        super(AcopioForm, self).__init__(*args, **kwargs)
        self.fields['socio'].empty_label = 'Buscar...'

apps/acopios/forms/socio.py
from crispy_forms.bootstrap import FormActions
from crispy_forms.helper import FormHelper, Layout
from crispy_forms.layout import Field, Div, Row
from django import forms

from ..models.models.socio import Socio
from backengo.utils.forms import smtSave, btnCancel, btnReset


class SocioForm(forms.ModelForm):

    class Meta:
        """Meta."""

        model = Socio
        exclude = ('estado',)
        Field = ('cod_socio', 'direccion', 'ciudad',)

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        self.object = kwargs.pop('object', None)
        super(SocioForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Div(Field('cod_socio',
                          placeholder="Ingrese el nombre de la empresa"),
                    css_class='col-md-5'),
                Div(Field('tipodoc'), css_class='col-md-4'),
                Div(Field('numdoc', placeholder="Ingrese un número"),
                    css_class='col-md-3'),
            ),
            Row(
                Div(Field('representante_legal',
                          placeholder="Ingrese el nombre completo"),
                    css_class='col-md-5'),
                Div(Field('direccion', placeholder="Ingrese un dirección"),
                    css_class='col-md-4'),
                Div(Field('ciudad', placeholder="Ingrese un número"),
                    css_class='col-md-3'),
            ),
            Row(
                Div(Field('email', placeholder="Ingrese un correo"),
                    css_class='col-md-4'),
                Div(Field('enti_bancaria', placeholder="Ingrese el nombre"),
                    css_class='col-md-4'),
                Div(Field('num_cuenta', placeholder="Ingrese un número"),
                    css_class='col-md-4'),
            ),
            Div(Row(
                FormActions(
                    smtSave(),
                    btnCancel(),
                    btnReset(),
                ),
            ), css_class='modal-footer',),
        )

apps/clinica/forms/atenciones.py
#encoding: utf-8
from django import forms

from django.utils.translation import ugettext_lazy as _
from django.utils.text import capfirst, get_text_list
from crispy_forms.helper import FormHelper, Layout
from crispy_forms.layout import Field, Div, Row, HTML
from crispy_forms.bootstrap import FormActions, TabHolder, Tab, InlineRadios, InlineCheckboxes

from backengo.utils.forms import smtSave, btnCancel, btnReset

from django.utils.timezone import get_current_timezone
from datetime import datetime

from ..models.atenciones import Atenciones, ArchivosAdjuntos

class AtencionesForm(forms.ModelForm):
    """Tipo Documeto Form."""
    class Meta:
        """Meta."""
        model = Atenciones
        exclude = ('colamedica',)
        fields = []

apps/clinica/templates/clinica/form/atencion.html
{% extends "main/dashboard.html" %}
{% load i18n crispy_forms_tags staticfiles %}
{% load l10n %}


{% block style %}
<link href="{% static 'bootstrap-chosen-master/bootstrap-chosen.css' %}" rel="stylesheet">
{% endblock style %}

{% block headjs %}
<script src="{% static 'bootstrap-chosen-master/chosen.jquery.js' %}"></script>
<script>
  $(function() {
	$('.chosen-select').chosen();
	$('.chosen-select-deselect').chosen({ allow_single_deselect: true });
  });
</script>
{% endblock %}

{% block breadcrumbs_item %}
<li><a href="/clinica/colamedica/listar/">{% trans 'Cola' %} {% trans 'Medica' %}</a></li>
<li class="active">{{ opts.verbose_name_plural|capfirst }}</li>
{% endblock breadcrumbs_item %}

{% block content_title %}
{% endblock content_title %}

{% block content %}

{% crispy form %}

{% endblock %}

{% block extrajs %}
{{ block.super }}

<script type="text/javascript">

$('#id_fecha_programada').datetimepicker({
	format: 'YYYY-MM-DD',
		//format: 'YYYY-MM-DD hh:mm:ss', //pata datatimes
		language: '{{ LANGUAGE_CODE }}',
		pickTime: false,
		//showMeridian: true,
		autoclose: true,
		todayHighlight: true,
	});


</script>
{% endblock extrajs %}

apps/clinica/templates/clinica/form/colamedica.html
{% extends "main/dashboard.html" %}
{% load i18n crispy_forms_tags %}
{% load l10n %}

{% block breadcrumbs_item %}
<li><a href="/clinica/colamedica/listar/">{{ opts.verbose_name_plural|capfirst }}</a></li>
<li class="active">{{ title }}</li>
{% endblock breadcrumbs_item %}

{% block page_title %}
	<i class="fa fa-paw"></i>dddddddddddd
	{{ opts.verbose_name_plural|capfirst }}
	<small>
		{{ subtitle }}
	</small>
{% endblock page_title %}

{% block page_content %}

	{% crispy form %}

{% endblock page_content %}

{% block extrajs %}
{% endblock extrajs %}

apps/clinica/templates/clinica/form/consulta.html
{% extends "main/dashboard.html" %}
{% load i18n crispy_forms_tags %}
{% load l10n %}

{% block breadcrumbs_item %}
<li><a href="/clinica/consulta/listar/">{{ opts.verbose_name_plural|capfirst }}</a></li>
<li class="active">{{ title }}</li>
{% endblock breadcrumbs_item %}

{% block content_title %}
<h3><i class="fa fa-paw"></i> {{ opts.verbose_name_plural|capfirst }} | <small>{{ subtitle }}</small></h3>
{% endblock content_title %}

{% block content %}
<div class="ui-widget">
  <label for="tags3">Tags: </label>
  <input id="tags3">
</div>
{% crispy form %}
{% endblock %}

{% block extrajs %}
{{ block.super }}
<script type="text/javascript">
	$(function() {
		$("#tags3").autocomplete({
			minLength:1,
			source: "/clinica/consulta/solo_url/"
		});
	});
</script>

{% endblock extrajs %}

apps/clinica/templates/clinica/form/historia.html
{% extends "main/dashboard.html" %}
{% load i18n crispy_forms_tags %}
{% load l10n %}

{% block style %}
<style media="screen">
	.form-control-mascota{
		border-color: #00796b;
	    background: #02a290 !important;
	    color: #fff;
	    font-size: 1.1em;
		cursor: pointer !important;
	}
	.subtitle-mascota{
		margin-top: 9px;
		font-size: 1.6em;
		color: #212121;
	}
	#div_id_num_historia{
		margin-bottom: 5px;
	}
	.div-mascota-forms{
		box-shadow:  1px 1px 1px 1px #009688;
		margin-bottom: 20px;
		padding: 7px 5px;
		border-radius: 10px;
	}

	.estado-historia{
		display: none;
	}
</style>
{% endblock style %}
{% block breadcrumbs_item %}
<li><a href="/clinica/historia/listar/">{{ opts.verbose_name_plural|capfirst }}</a></li>
<li class="active">{{ title }}</li>
{% endblock breadcrumbs_item %}

{% block page_title %}
    <i class="fa fa-list-alt"></i> {{ subtitle }} {{cantidad}} dsdsddddddddd
{% endblock page_title %}

{% block page_content %}

{% crispy form %}

{% endblock page_content %}

{% block extrajs %}
{{ block.super }}

<script type="text/javascript">
$('#id_num_historia').attr('readonly', true);
$('#id_nombre').attr('readonly', true);
$('#id_duenho option:not(:selected)').attr('disabled',true);
$('#id_fecha_nacimiento option:not(:selected)').attr('disabled',true);

if('{{cantidad}}'<=9){
	$("#id_num_historia").val('0000{{cantidad}}');
}
else if ('{{cantidad}}'<=99) {
	$("#id_num_historia").val('000{{cantidad}}');
}
else if('{{cantidad}}'<=999) {
	$("#id_num_historia").val('00{{cantidad}}');
}
else if('{{cantidad}}'<=9999){
	$("#id_num_historia").val('0{{cantidad}}');
}
else{
	$("#id_num_historia").val('{{cantidad}}');
}

$("#id_historia").attr('checked', true);

$('#id_caracter, #id_actividad,#id_habitar,#id_alimentacion,#id_aptitup').append('<option value selected="selected" diseabled>Elige una opcion..</option>');
$('#id_fecha_nacimiento').datetimepicker({
	format: 'YYYY-MM-DD',
		//format: 'YYYY-MM-DD hh:mm:ss', //pata datatimes
		language: '{{ LANGUAGE_CODE }}',
		pickTime: false,
		//showMeridian: true,
		autoclose: true,
		todayHighlight: true,
	});

</script>
{% endblock extrajs %}

apps/clinica/templates/clinica/form/mascota.html
{% extends "main/dashboard.html" %}
{% load i18n crispy_forms_tags staticfiles %}
{% load l10n  %}

{% block style %}
<link rel="stylesheet" href="{% static 'assets/css/bootstrap-duallistbox.css' %}" />
<style media="screen">
input[type=checkbox].ace.ace-switch.ace-switch-7 + .lbl::before {
  content: "NO\a0\a0\a0\a0\a0\a0\a0\a0\a0\a0\a0\a0\a0\a0SI" !important;
  }
    .finalizar{
        display: none;
    }
</style>
{% endblock style %}
{% block headjs %}
{% endblock %}
{% block breadcrumbs_item %}
<li><a href="/clinica/mascota/listar/">{{ opts.verbose_name_plural|capfirst }}</a></li>
<li class="active">{{ title }}</li>
{% endblock breadcrumbs_item %}

{% block page_title %}
<i class="fa fa-paw"></i> {{ subtitle }}
{% endblock page_title %}
{% block page_content %}
{% crispy form %}
{% endblock %}

{% block extrajs %}
{{ block.super }}

<script src="{% static 'assets/js/jquery.bootstrap-duallistbox.js' %}"></script>
<script src="{% static 'assets/js/fuelux/fuelux.wizard.js' %}"></script>
<script src="{% static 'assets/js/ace/elements.wizard.js' %}"></script>
<script type="text/javascript">

//$("[name='esterelizado']").bootstrapSwitch();
$(".wizard-actions button").addClass('finalizar');

$("#id_esterelizado").addClass("ace ace-switch ace-switch-7");

var tamaño = ['next'];
    $("#next").click(function () {
        var data = $(this).val('data-last');
        for (var i = 0; i <  data.length; i++) {
            var dataa = data[i].innerText;
        }
        tamaño.push(dataa);
        console.log(tamaño);
        if (tamaño.length===4) {
            $(".wizard-actions button").removeClass('finalizar');
            $(this).addClass('finalizar');
        }
    });

    $("#prev").click(function () {
        var dato = $(this).val('data-last');
        console.log(dato);
        tamaño.splice(1,1);
        console.log(tamaño);
        if (dato!='Finish') {
            $(".wizard-actions button").addClass('finalizar');
            $("#next").removeClass('finalizar');
        }
    });


    jQuery(function($) {

        var $validation = false;
        $('#fuelux-wizard-container')
        .ace_wizard({
            //step: 2 //optional argument. wizard will jump to step "2" at first
            //buttons: '.wizard-actions:eq(0)'
        })
        .on('actionclicked.fu.wizard' , function(e, info){
            if(info.step == 1 && $validation) {
                if(!$('#validation-form').valid()) e.preventDefault();
            }
        })
        .on('finished.fu.wizard', function(e) {

        }).on('stepclick.fu.wizard', function(e){
            //e.preventDefault();//this will prevent clicking and selecting steps
        });
    })

    $(".wizard-actions #next").attr('disabled', 'disabled');


$('#id_fecha_nacimiento').datetimepicker({
	format: 'YYYY-MM-DD',
		//format: 'YYYY-MM-DD hh:mm:ss', //pata datatimes
		language: '{{ LANGUAGE_CODE }}',
		pickTime: false,
		//showMeridian: true,
		autoclose: true,
		todayHighlight: true,
	});

</script>
{% endblock extrajs %}