apps/clinica/urls.py
from django.conf.urls import url


from .views.atencionviews import AtencionHistoriaListView, AtencionListView, AtencionCreateView, AtencionTerminadaView
from .views.colamedicaviews import ColaMedicaListView,MainCreateView, ColaMedicaDeleteView, ColasMedicasListView, BuscarCliente
from .views.vacunacionviews import  get_drugs, BuscarProducto
from .views.consulta_diagnostico import  get_diagnosticos
from .views.tratamientos import  get_tratamientos
from .views.consulta_pruebas_auxiliares import  get_pruebas_auxiliares
from .views.historiaviews import HistoriasListView, HistoriaFichaListView,  HistoriaMascotaDetailView, HistoriaMascotaCreateView
from .views.mascotaviews import MascotaListView, MascotaCreateView, MascotaPerfilView, MascotaHistoriaListView, MascotaUpdateView, MascotaUpdateActiveView
from .views.cliente import ClienteListView, ClienteCreateView, ClienteUpdateView, ClienteDeleteView, PostClienteAjax
from .views.cunsulta import ConsultaCreateView, ConsultaUpdateView,  ConsultaDeleteView
from .views.notas import NotasCreateView, upload, upload_delete
from .views.vacunacion import VacunacionCreateView, PostVacunacionAjax
from .views.colamedicaviews import MainCreateView,VentasView
urlpatterns = [
    url(r'^api/get_drugs/', get_drugs, name='get_drugs'),
    url(r'^api/diagnostico/', get_diagnosticos, name='get_diagnosticos'),
    url(r'^api/pruebas_auxiliares/', get_pruebas_auxiliares, name='get_pruebas_auxiliares'),
    url(r'^api/tratamientos/', get_tratamientos, name='get_tratamientos'),

    #BUSQUEDAS-URLS

    url(r'^producto/search/',
        BuscarProducto, name='search_producto_recepcion'),
    url(r'^cliente/search/',BuscarCliente, name='search_cliente'),



#Atencion Medica
    url(r'^atenciones/listar/(?P<mascota_pk>[^/]+)/(?P<colamedica_pk>[^/]+)$', AtencionListView.as_view(), name="historia_list"),
    url(r'^atenciones/historia/(?P<mascota_pk>[^/]+)/(?P<colamedica_pk>[^/]+)$', AtencionHistoriaListView.as_view(), name="atencion_historia_list"),
    url(r'^atenciones/crear/(?P<mascota_pk>[^/]+)/(?P<colamedica_pk>[^/]+)/$', AtencionCreateView.as_view(), name="atenciones_add"),
    url(r'^atencion/terminada/(?P<state>[\w\d\-]+)/(?P<pk>.*)/$',
        AtencionTerminadaView.as_view(), name='atencion_satate'),

#Consultas
    url(r'^atencion/consulta/(?P<mascota_pk>[^/]+)/(?P<colamedica_pk>[^/]+)$', ConsultaCreateView.as_view(), name='consulta_add'),
    url(r'^atencion/consulta/editar/(?P<mascota_pk>[^/]+)/(?P<colamedica_pk>[^/]+)/(?P<atencion_pk>[^/]+)/(?P<pk>.*)/$', ConsultaUpdateView.as_view(), name='consulta_update'),
    url(r'^atencion/consulta/eliminar/(?P<mascota_pk>[^/]+)/(?P<colamedica_pk>[^/]+)/(?P<pk>.*)/$', ConsultaDeleteView.as_view(), name="consulta_delete"),

    #Notas
    url(r'^atencion/notas/(?P<mascota_pk>[^/]+)/(?P<colamedica_pk>[^/]+)/(?P<atencion_pk>[^/]+)/$', NotasCreateView.as_view(), name='nota_add'),

    #Archivos

    #Vacunacion
    url(r'^atencion/vacunacion/(?P<mascota_pk>[^/]+)/(?P<colamedica_pk>[^/]+)/$', VacunacionCreateView.as_view(), name='vacuna_add'),
    url(r'^atencion/vacunacion/crear-ajax/$', PostVacunacionAjax, name="post_vacunacion_ajax"),

    #Cola Medica
    url(r'^colamedica/listar/$', ColaMedicaListView.as_view(), name="listar_medica"),
    url(r'^colamedica/lista/$', ColasMedicasListView.as_view(), name="lista_medica"),

    url(r'^colamedica/crear/$', MainCreateView.as_view(), name="crear_medica"),
    url(r'^ventas/$', VentasView.as_view(), name="crear_venta"),
    url(r'^colamedica/eliminar/(?P<pk>.*)/$', ColaMedicaDeleteView.as_view(), name="eliminar_medica"),

    #url(r'^colamedica/detail/(?P<pk>.*)/$', AtencionMedicaView.as_view(), name='colamedica_detail'),



    # Historia
    url(r'^historia/listar/$', HistoriasListView.as_view(), name="listar_historia"),
    url(r'^historia/ficha/(?P<mascota_pk>[^/]+)$', HistoriaFichaListView.as_view(), name="ver_ficha_clinica"),
    url(r'^historia/crear/(?P<cliente_pk>[^/]+)/(?P<mascota_pk>[^/]+)$',
        HistoriaMascotaCreateView.as_view(), name='crear_historia'),
    url(r'^historia/detail/(?P<pk>.*)/$',
        HistoriaMascotaDetailView.as_view(), name='historia_detail'),

    # Mascota
    url(r'^mascota/listar/(?P<cliente_pk>[^/]+)$',
        MascotaListView.as_view(), name="mascota_list"),
    url(r'^mascota/crear/(?P<cliente_pk>[^/]+)$',
        MascotaCreateView.as_view(), name="mascota_add"),
    url(r'^mascota/actualizar/(?P<pk>.*)/$',
        MascotaUpdateView.as_view(), name="actualizar_mascota"),
    url(r'^mascota/state/(?P<state>[\w\d\-]+)/(?P<pk>.*)/$',
        MascotaUpdateActiveView.as_view(), name='mascota-state'),
    url(r'^mascota/perfil/(?P<pk>.*)/$', MascotaPerfilView.as_view(), name="mascota_perfil_list"),
    url(r'^mascota/historia/(?P<mascota_pk>[^/]+)/$', MascotaHistoriaListView.as_view(), name="historia_list"),
    # ===================CLIENTE==========================
    url(r'^cliente/listar/$', ClienteListView.as_view(), name="cliente_list"),
    url(r'^cliente/crear/$', ClienteCreateView.as_view(), name="cliente_add"),
    url(r'^cliente/actualizar/(?P<pk>.*)/$',
        ClienteUpdateView.as_view(), name="cliente_upd"),
    url(r'^cliente/eliminar/(?P<pk>.*)/$',
        ClienteDeleteView.as_view(), name="cliente_del"),
    url(r'^cliente/crear/ajax$', PostClienteAjax, name="post_cliente_ajax"),
]

config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django import views as django_views

from apps.clinica.views.notas import upload, upload_delete

from apps.clivet.views.main import  MainView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/', django_views.i18n.javascript_catalog),
    # =============================================================
    #                           backengo
    # =============================================================
    url(r'^mod_backend/', include('apps.mod_backend.urls', namespace='mod_backend')),
    url(r'^space/', include('apps.space.urls', namespace='space')),
    url(r'^sad/', include('apps.sad.urls', namespace='sad')),
    url(r'^accounts/', include('apps.accounts.urls')),
    # =============================================================
    #                           clivet
    # =============================================================


    url( r'upload/', upload, name = 'jfu_upload' ),
    url( r'^delete/(?P<pk>\d+)$', upload_delete, name = 'jfu_delete' ),

    # url(r'^about/$', AboutView.as_view()),
    url(r'^$', MainView.as_view(), name='dashboard'),

    url(r'^', include('apps.clivet.urls', namespace='clivet')),
    url(r'^clinica/', include('apps.clinica.urls', namespace='clinica')),
    url(r'^ventas/', include('apps.ventas.urls', namespace='ventas')),
    url(r'^configuracion/', include('apps.configuracion.urls', namespace='configuracion')),
    url(r'^compras/', include('apps.compras.urls', namespace='compras')),
    url(r'^citas/', include('apps.citas.urls', namespace='citas')),
    url(r'^acopios/', include('apps.acopios.urls', namespace='acopios')),
    # TODO: Poner en la aplicacion que se usa
    url(r'^chaining/', include('smart_selects.urls')),
]

urlpatterns = urlpatterns + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

apps/clinica/models/atencion.py
# coding: utf-8 _*_
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.text import capfirst
from django.dispatch import receiver
from django.db.models import signals
from unicodedata import normalize
from django.core.exceptions import ValidationError
#Impors  Models
from ..models.colamedica import ColaMedica
from ..models.atenciones import Atenciones
from ..models.mascota import Mascota
from ..models.consulta import Diagnostico, Tratamiento, Pruebas, HallasgosClinicos

# Create your models here.
class Atencion(models.Model):
    atenciones = models.ForeignKey(Atenciones)
#Consulta
    motivo_atencion = models.CharField(max_length=300)
    temperatura = models.CharField(max_length=50)
    fc = models.CharField(max_length=50)
    fr = models.CharField(max_length=50)
    kg = models.CharField(max_length=50)
    porcentaje = models.CharField(max_length=50)
    tlc = models.CharField(max_length=50)
    anamnesis = models.CharField(max_length=200)
    hallasgos_clinicos = models.ManyToManyField(HallasgosClinicos, max_length=300)
    #diagnostico = models.ManyToManyField(Diagnostico, max_length=300)
    dx = models.CharField(max_length=300)
    pronostico = models.CharField(max_length=300)
    #pruebas_auxiliares = models.ManyToManyField(Pruebas, max_length=300)
    #tratamiento = models.ManyToManyField(Tratamiento, max_length=300)
    observacion = models.CharField(max_length=300)

    class Meta:
        verbose_name = "Atencion"
        verbose_name_plural = "Atenciones"
        permissions = (
            ('atencion', 'Can ALL atencion'),
        )
    def __str__(self):
        return "%s" % (self.motivo_atencion)

apps/clinica/models/vacunacion.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.text import capfirst
from django.dispatch import receiver
from django.db.models import signals
from unicodedata import normalize
from django.core.exceptions import ValidationError

from apps.ventas.models.Producto import Producto
from ..models.atenciones import Atenciones

TIPO_VACUNACION=(
    ('cita', "cita"),
    ('consulta', "consulta")
)

class Vacunacion(models.Model):
    atenciones = models.ForeignKey(Atenciones, blank=True)
    motivo = models.CharField(max_length= 150, blank=True)
    created_ath = models.DateTimeField(_(u'Fecha Creada'), auto_now_add=True)
    tipo_vacunacion = models.CharField(_(u'Tipo Vacunación'), max_length=50, choices = TIPO_VACUNACION, blank=True)
    vacuna = models.ForeignKey(Producto, max_length=100,  blank=True)
    dosis = models.CharField(max_length=50, blank=True)
    observacion = models.TextField(max_length=100, null=True, blank=True)

    class Meta:
        verbose_name = "vacunacion"
        verbose_name_plural = "vacunaciones"
        permissions = (
            ('vacunaciones', 'Can ALL vacunaciones'),
        )
    def __str__(self):
        return "%s" % (self.motivo)

apps/clinica/forms/atenciones.py
#encoding: utf-8
from django import forms

from django.utils.translation import ugettext_lazy as _
from django.utils.text import capfirst, get_text_list
from crispy_forms.helper import FormHelper, Layout
from crispy_forms.layout import Field, Div, Row, HTML
from crispy_forms.bootstrap import FormActions, TabHolder, Tab, InlineRadios, InlineCheckboxes

from backengo.utils.forms import smtSave, btnCancel, btnReset

from django.utils.timezone import get_current_timezone
from datetime import datetime

from ..models.atenciones import Atenciones, ArchivosAdjuntos

class AtencionesForm(forms.ModelForm):
    """Tipo Documeto Form."""
    class Meta:
        """Meta."""
        model = Atenciones
        exclude = ('colamedica',)
        fields = []

apps/clinica/forms/cliente.py
u"""Módulo Cliente Form."""

from django import forms
from ..models.cliente import Cliente
from apps.params.models import IDENTITY_TYPE_CHOICES
from django.utils.translation import ugettext_lazy as _
from crispy_forms.layout import Field, Div, Row, HTML
from crispy_forms.bootstrap import FormActions, TabHolder, Tab
from crispy_forms.helper import FormHelper, Layout
from backengo.utils.forms import smtSave, btnCancel, btnReset
from django.utils.text import capfirst, get_text_list


class ClienteForm(forms.ModelForm):
    u"""Cliente Form."""
    nombre = forms.CharField(max_length=100)
    apellidos = forms.CharField(max_length=100)
    numero = forms.IntegerField(required=False)
    tipo_documento = forms.ChoiceField(choices=IDENTITY_TYPE_CHOICES)
    fecha_de_nacimiento = forms.DateField(
        widget=forms.DateInput(attrs={'class': 'datepicker', }),
        required=False)
    # apellido = forms.CharField(max_length=100,widget=forms.Textarea)
    # sender = forms.EmailField()
    # cc_myself = forms.BooleanField(required=False)
    # producto = forms.ModelChoiceField(
    #     queryset=Producto.objects.all(),
    #     required=False, label="", help_text="")
    # data_venta = forms.CharField(
    #     required=False, widget=forms.TextInput(attrs={'type': 'hidden'}))
    #  hoice_field = forms.ChoiceField(widget=forms.RadioSelect,
    #                                 choices=CHOICES)

    class Meta:
        """Meta."""
        model = Cliente
        exclude = ('persona',)
        fields = ('direccion', 'ciudad', 'email', 'telefono')

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        self.object = kwargs.pop('object', None)
        super(ClienteForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Div(Field('nombre',  placeholder='Ingrese un nombre',
                          css_class='input-required'),
                    css_class='col-md-3'),
                Div(Field('apellidos', placeholder='Ingrese sus apellidos'),
                    css_class='col-md-4'),
                Div(Field('tipo_documento',), css_class='col-md-2'),
                Div(Field('numero', placeholder='Ingrese un número'),
                    css_class='col-md-3'),
            ),
            Row(
                Div(Field('fecha_de_nacimiento', placeholder='YYYY-MM-DD'),
                    css_class='col-md-2'),
                Div(Field('ciudad', placeholder='Ingrese el nombre'),
                    css_class='col-md-2'),
                Div(Field('direccion', placeholder='Ingrese una dirección'),
                    css_class='col-md-3'),
                Div(Field('email', placeholder='example@gmail.com'),
                    css_class='col-md-3'),
                Div(Field('telefono', placeholder='Ingrese el número'),
                    css_class='col-md-2'),
            ),
            Div(Row(
                FormActions(
                    smtSave(),
                    btnCancel(),
                    btnReset(),
                ),
            ), css_class='modal-footer',),
        )

apps/clinica/forms/colamedicaform.py
#encoding: utf-8
from django import forms

from django.utils.translation import ugettext_lazy as _
from django.utils.text import capfirst, get_text_list
from crispy_forms.helper import FormHelper, Layout
from crispy_forms.layout import Field, Div, Row, HTML
from crispy_forms.bootstrap import FormActions, TabHolder, Tab, StrictButton
from backengo.utils.forms import smtSave, btnCancel, btnReset
from django.utils.timezone import get_current_timezone
from datetime import datetime
from ..models.colamedica import ColaMedica
from ..models.mascota import Mascota
from apps.clinica.models.cliente import Cliente
from apps.sad.models import User

class ColaMedicaForm(forms.ModelForm):
    """Tipo Documeto Form."""
    cliente = forms.ModelChoiceField(
            queryset=Cliente.objects.all(), required=False, )

    mascotas = forms.ModelChoiceField(
            queryset=Mascota.objects.all(), required=False, )
    class Meta:
        """Meta."""
        model = ColaMedica
        exclude = ()
        fields = ['fuente_atencion','mascota','descripcion','medico',]

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        self.object = kwargs.pop('object', None)

        super(ColaMedicaForm, self).__init__(*args, **kwargs)

        self.fields['descripcion'] = forms.CharField(
            label=capfirst(_(u'Descripcion:')), required=True,
            help_text=u'<small class="help-error"></small> %s' % _(
                u' '),
        )
        self.fields['medico'] = forms.ModelChoiceField(
                    queryset=User.objects.filter(groups=10), required=False, )
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_class = 'js-validate'
        self.helper.layout = Layout(
            Row(
                Div(
                    Field('mascota',  css_class='input-required', readonly=True),
                        css_class="col-md-4"),
                Div(
                    Field('medico', css_class='input-required'),
                        css_class="col-md-4"),
                Div(
                    Field('fuente_atencion', placeholder="Introdusca el color", css_class='input-required'),
                        css_class="col-md-4"),
                Div(
                    Field('descripcion', ),
                        css_class="col-md-12"),
            ),
            Row(
                Div(
                    FormActions(
                        smtSave(),
                    ),
                css_class="col-md-12 btn-controls"),
            ),
        )

apps/clinica/templates/clinica/historial/index.html
{% extends "main/dashboard.html" %}
{% load i18n crispy_forms_tags staticfiles %}
{% load i18n app_security %}
{% load l10n humanize %}

{% block style %}
<style media="screen">
.disabled {
pointer-events: none;
cursor: default;
}
</style>{% endblock style %}

{% block breadcrumbs_item %}
<li><a href="#">{{ opts.verbose_name_plural|capfirst }}</a></li>
<li class="active">{{ title }}</li>
{% endblock breadcrumbs_item %}

{% block page_title %}
<span class="fa fa-hospital-o purple">  {{mascota_nombre|upper}} /<small>{{mascota_raza|upper}} -- {{mascota_genero|upper}},</small> <label>PROPIETARIO:<small>{{ mascota_dueño|upper }}</small></label></span>
{% endblock page_title %}

{% block page_content %}
<!-- #section:elements.tab -->
<div class="tabbable">
    <ul class="nav nav-tabs" id="myTab">
        <li class="active">
            <a data-toggle="tab" href="#perfil">
                <i class="green ace-icon fa fa-github bigger-120"></i>
                Perfil
            </a>
        </li>

        <li>
            <a data-toggle="tab" href="#editar">
                <i class="purple ace-icon fa fa-edit bigger-120"></i>
                Editar
            </a>
        </li>

        <li>
            <a data-toggle="tab" href="#historia_compras">
                <i class="light-blue ace-icon fa fa-github bigger-120"></i>
                Historial de compras
            </a>
        </li>

        <li>
            <a data-toggle="tab" href="#historia_medica">
                <i class="red ace-icon fa fa-stethoscope bigger-120"></i>
                Historia Clinica
            </a>
        </li>
    </ul>

    <div class="tab-content">
        <div id="perfil" class="tab-pane fade in active">
            <p>Raw denim you probably haven't heard of them jean shorts Austin.</p>

        </div>

        <div id="editar" class="tab-pane fade">
            <p>Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid.</p>
        </div>

        <div id="historia_compras" class="tab-pane fade">
            <p>Etsy mixtape wayfarers, ethical wes anderson tofu before they sold out mcsweeney's organic lomo retro fanny pack lo-fi farm-to-table readymade.</p>
        </div>

        <div id="historia_medica" class="tab-pane fade">

            <div id="tab-historia-medica">
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Detalles de la Cita</h4>
            </div>
            <div class="modal-body">
                <form action="" method="post" name="vacunacion-form" id="vacunacion-form">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-12">
                            <div id="div_id_motivo" class="form-group">
                                <label for="id_motivo" class="control-label ">Motivo</label>
                                <div class="controls ">
                                    <input class="textinput textInput form-control" id="id_motivo" maxlength="150" name="motivo" placeholder="Ingrese el motivo de vacunación" type="text">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div id="div_id_vacuna" class="form-group">
                                <label for="id_vacuna" class="control-label ">Vacuna</label>
                                <div class="controls ">
                                    <select class="form-control" name="vacuna"  id="id_vacuna">
                                        {% for d in vacunas %}
                                            <option value="{{d.id}}">{{d.nombre}}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div id="div_id_dosis" class="form-group">
                                <label for="id_dosis" class="control-label ">Dosis</label>
                                <div class="controls ">
                                    <input class="textinput textInput form-control" id="id_dosis" maxlength="150" name="motivo" placeholder="Dosis de la vacuna aplicada" type="text">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div id="div_id_observacion" class="form-group"> <label for="id_observacion" class="control-label ">Observacion</label>
                                <div class="controls ">
                                    <textarea class="textarea form-control"id="id_observacion" maxlength="100" name="observacion" placeholder="Ingrese un la nota" rows="3"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
                <div class="alert alert-danger hide" role="alert" id="success_message_vacunacion_error"></div>
            </div>
            <div class="modal-footer" id="vacunacion_controls">
                <div class="form-group">
                    <div class="controls">
                        <button type="submit" name="submit" class="btn btn-primary text-bold" id="save-vacunacion" title="Grabar">
                            <i class="btn-icon-onlyx fa fa-save"></i> <span class="hidden-xsx"> Grabar</span>
                        </button>
                        <button type="reset" name="reset" class="btn btn btn-default text-bold" id="reset-id-reset" title="Reset">
                            <i class="btn-icon-onlyx fa fa-undo"></i> <span class="hidden-xs"> Limpiar</span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="Modalarchivo" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Detalles de la Cita</h4>
            </div>
            <div class="modal-body">
                <div id="archivo_modal">
                    {% load jfutags %}
                    {% jfu 'clinica/archivos_form.html' %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock page_content %}

{% block extrajs %}
{{ block.super }}

<script type="text/javascript">



$.ajax({
    url: '/clinica/atenciones/historia/{{id_mascota }}/{{id_cola_medica }}',
    type: 'GET',
})
.done(function(d) {
    $("#tab-historia-medica").html(d);
    console.log("success");
})
.fail(function() {
    console.log("error");
})
.always(function() {
    console.log("complete");
});

    $('#myModal').on('shown.bs.modal', function () {
        $(this).modal('show');
    });

    $('#save-vacunacion').click(function() {
        var formArray = $("#vacunacion-form").serializeArray();
        var formJson = JSON.stringify(formArray);
        console.log(formArray);
        if (formArray[1].value.trim().length > 0 &&
            formArray[2].value.trim().length > 0 &&
            formArray[3].value.trim().length > 0 ) {
            $.ajax({
                    url: '{% url "clinica:post_vacunacion_ajax" %}',
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        motivo: formArray[1].value,
                        vacuna: formArray[2].value,
                        dosis: formArray[3].value,
                        observacion: formArray[4].value,
                    },
                })
                .done(function(d) {
                    $('#myModal').modal('hide');
                    console.log("Registro satisfactoriamente");
                    var html = "";
                    html += '<div class="alert alert-success " role="alert"><button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>Se aplico la vacuna satisfactoriamente.</div>'
                    $.ajax({
                        url: '/clinica/atenciones/historia/{{id_mascota }}/{{id_cola_medica }}',
                        type: 'GET',
                    })
                    .done(function(d) {
                        $("#tab-historia-medica").html(d);
                        console.log("success");
                    })
                    .fail(function() {
                        console.log("error");
                    })
                    .always(function() {
                        console.log("complete");
                    });
                    $('#flash-message').html(html)

                })
                .fail(function() {
                    console.log("error");
                })
                .always(function() {
                    console.log("complete");
                });
        } else {
            $('#success_message_vacunacion_error').attr('class', 'alert alert-danger').text("Revise los datos ingresados nuevamente.");
        }
    });



    $('#update_vacunacion').click(function() {

        console.log("ddddddddddddddd");
        alert("golaaaaa");

    });


function activaTab(tab){
    $('.nav-tabs a[href="#' + tab + '"]').tab('show');
};
activaTab('historia_medica');



    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');
    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });
</script>
{% endblock extrajs %}