apps/accounts/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView

from .views import LoginView, LogOutView, SignUpView, index, load_access, \
    EnterpriseAssociationCreateView
from django.contrib.auth import views as auth_views


accounts_patterns = [
    url(r'^', index, name='index'),
]

urlpatterns = [
    # Examples:
    # url(r'^$', 'plateo.views.home', name='home'),
    url(r'^load_access/(?P<headquar_id>.*)/(?P<module_id>.*)/$',
        load_access, name='load_access'),
    url(r'^add_enterprise/$',
        EnterpriseAssociationCreateView.as_view(), name='add_enterprise'),
    url(r'^$', include(accounts_patterns, namespace='accounts')),

    url(r'^login/$', LoginView.as_view(), name='login'),
    # url(r'^logout/$', auth_views.logout,
    #    {'template_name': 'registration/logged_out.html'}, name='logout'),

    url(r'^logout/$', LogOutView.as_view(), name='logout'),

    url(r'^register/', SignUpView.as_view(), name='register'),

    url(r'^password_reset/$',
        auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$',
        auth_views.password_reset_done, name='password_reset_done'),
    # Support old style base36 password reset links; remove in Django 1.7
    #url(r'^reset/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #    auth_views.password_reset_confirm_uidb36),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete,
        name='password_reset_complete'),


    url(r'^password/change/$', auth_views.password_change,
        name='password_change'),
    url(r'^password/change/done/$', auth_views.password_change_done,
        name='password_change_done'),


]

backengo/accounts/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView

from .views import LoginView, LogOutView, SignUpView, index, load_access, \
    EnterpriseAssociationCreateView
from django.contrib.auth import views as auth_views


accounts_patterns = [
    url(r'^', index, name='index'),
]

urlpatterns = [
    # Examples:
    # url(r'^$', 'plateo.views.home', name='home'),
    url(r'^load_access/(?P<headquar_id>.*)/(?P<module_id>.*)/$',
        load_access, name='load_access'),

    url(r'^add_enterprise/$',
        EnterpriseAssociationCreateView.as_view(), name='add_enterprise'),
    url(r'^$', include(accounts_patterns, namespace='accounts')),

    url(r'^login/$', LoginView.as_view(), name='login'),
    # url(r'^logout/$', auth_views.logout,
    #    {'template_name': 'registration/logged_out.html'}, name='logout'),

    url(r'^logout/$', LogOutView.as_view(), name='logout'),

    url(r'^register/', SignUpView.as_view(), name='register'),

    url(r'^password_reset/$',
        auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$',
        auth_views.password_reset_done, name='password_reset_done'),
    # Support old style base36 password reset links; remove in Django 1.7
    #url(r'^reset/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #    auth_views.password_reset_confirm_uidb36),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete,
        name='password_reset_complete'),


    url(r'^password/change/$', auth_views.password_change,
        name='password_change'),
    url(r'^password/change/done/$', auth_views.password_change_done,
        name='password_change_done'),


]

config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django import views as django_views

from apps.clinica.views.notas import upload, upload_delete

from apps.clivet.views.main import  MainView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/', django_views.i18n.javascript_catalog),
    # =============================================================
    #                           backengo
    # =============================================================
    url(r'^mod_backend/', include('apps.mod_backend.urls', namespace='mod_backend')),
    url(r'^space/', include('apps.space.urls', namespace='space')),
    url(r'^sad/', include('apps.sad.urls', namespace='sad')),
    url(r'^accounts/', include('apps.accounts.urls')),
    # =============================================================
    #                           clivet
    # =============================================================


    url( r'upload/', upload, name = 'jfu_upload' ),
    url( r'^delete/(?P<pk>\d+)$', upload_delete, name = 'jfu_delete' ),

    # url(r'^about/$', AboutView.as_view()),
    url(r'^$', MainView.as_view(), name='dashboard'),

    url(r'^', include('apps.clivet.urls', namespace='clivet')),
    url(r'^clinica/', include('apps.clinica.urls', namespace='clinica')),
    url(r'^ventas/', include('apps.ventas.urls', namespace='ventas')),
    url(r'^configuracion/', include('apps.configuracion.urls', namespace='configuracion')),
    url(r'^compras/', include('apps.compras.urls', namespace='compras')),
    url(r'^citas/', include('apps.citas.urls', namespace='citas')),
    url(r'^acopios/', include('apps.acopios.urls', namespace='acopios')),
    # TODO: Poner en la aplicacion que se usa
    url(r'^chaining/', include('smart_selects.urls')),
]

urlpatterns = urlpatterns + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

apps/accounts/models.py
from django.db import models

# Create your models here.

apps/space/models.py
# _*_ coding: utf-8 _*_
"""
@copyright   Copyright (c) 2014 Submit Consulting
@author      Angel Sullon (@asullom)
@package     space

Descripcion: Registro de los modelos de la app space
"""
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.text import capfirst
from django.dispatch import receiver
from django.db.models import signals
from unicodedata import normalize
from django.core.exceptions import ValidationError

# models
#from apps.params.models import Locality

# managers
#from .managers import SolutionManager

# others
#from django.utils import timezone
#from django.core.exceptions import NON_FIELD_ERRORS
#from django.template.defaultfilters import slugify

GOVERMENT = 'GOVERMENT'
PRIVATE = 'PRIVATE'
MIXED = 'MIXED'
OTHERS = 'OTHERS'
TYPE_CHOICES = (
    (GOVERMENT, _('Government')),
    (PRIVATE, _('Private')),
    (MIXED, _('Mixed')),
    (OTHERS, _('Others'))
)


def unique_name(value):
    if value == 'angel':
        raise ValidationError(u'%s is not an angel' % value)


class Solution(models.Model):

    """
    Tabla que contiene las soluciones o planes o servicios del sistema
    """
    name = models.CharField(capfirst(_('name')), max_length=50)
    description = models.TextField(_('Description'), null=True, blank=True)
    price = models.FloatField(_('Price'), null=True, blank=True)
    is_active = models.BooleanField(capfirst(_('active')), default=True)

    created_at = models.DateTimeField(_('Created at'), auto_now_add=True)
    updated_at = models.DateTimeField(_('Updated at'), auto_now=True)

    test_image = models.ImageField(
        _('Test image'), upload_to='test_images',
        default='test_images/default.png', null=True, blank=True)
    test_date = models.DateTimeField(_('Test date'),
                                     null=True, blank=True)

    class Meta:
        verbose_name = _('Solution')
        verbose_name_plural = _('Solutions')
        permissions = (
            ('solution', 'Can ALL solution'),
        )
        unique_together = ('name',)

    def __str__(self):
        return self.name

    def validate_unique(self, exclude=None):
        if normalize('NFKD', self.name).encode('ascii', 'ignore').lower() in list(
            normalize('NFKD', c['name']).encode('ascii', 'ignore').lower()
            for c in self.__class__.objects.values('name').exclude(pk=self.pk)
        ):
            raise ValidationError({
                'name':
                (_(u'%(model_name)s with this %(field_label)s already exists.') % {
                'model_name': _('Solution'),
                'field_label': capfirst(_('name')),
                },),
            })

        super(Solution, self).validate_unique(exclude=exclude)


class Association(models.Model):

    """
    Tabla que contiene las asociaciones suscritas a un plan
    """

    name = models.CharField(capfirst(_('name')), max_length=50)
    logo = models.ImageField(
        _('Logo'),
        upload_to='associations', default='associations/default.png')
    type_a = models.CharField(
        _('Type'),
        max_length=10, choices=TYPE_CHOICES, default=PRIVATE)
    is_active = models.BooleanField(capfirst(_('active')), default=True)
    is_actived = models.BooleanField(_('Actived'), default=False)

    created_at = models.DateTimeField(_('Created at'), auto_now_add=True)
    updated_at = models.DateTimeField(_('Updated at'), auto_now=True)

    solution = models.ForeignKey(
        Solution, verbose_name=_('Solution'), null=True, blank=True)

    class Meta:
        verbose_name = _('Association')
        verbose_name_plural = _('Associations')
        permissions = (
            ('association', 'Can ALL association'),
        )
        unique_together = ('name',)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if normalize('NFKD', u'%s' % self.name).encode('ascii', 'ignore').lower() in list(
                normalize('NFKD', u'%s' % c['name']).encode('ascii', 'ignore').lower() for c in Association.objects.values('name').exclude(pk=self.pk)
        ):
            raise Exception(_(u'%(model_name)s with this %(field_label)s already exists.') % {
                'model_name': _('Association'),
                'field_label': capfirst(_(u'name')),
            })
        super(Association, self).save(*args, **kwargs)


class Enterprise(models.Model):

    """
    Tabla que contiene las empresas suscritas a un plan
    """

    name = models.CharField(capfirst(_('name')), max_length=50)
    #name_sm = models.CharField(capfirst(_('siglas')), max_length=50)
    logo = models.ImageField(
        _('Logo'), upload_to='enterprises', default='enterprises/default.png')
    tax_id = models.CharField(_('Tax id'), max_length=50)
    type_e = models.CharField(
        _('Type'),
        max_length=10, choices=TYPE_CHOICES, default=PRIVATE)
    is_active = models.BooleanField(capfirst(_('active')), default=True)
    is_actived = models.BooleanField(_('Actived'), default=False)

    created_at = models.DateTimeField(_('Created at'), auto_now_add=True)
    updated_at = models.DateTimeField(_('Updated at'), auto_now=True)

    solution = models.ForeignKey(
        Solution, verbose_name=_('Solution'), null=True, blank=True)

    class Meta:
        verbose_name = _('Enterprise')
        verbose_name_plural = _('Enterprises')
        permissions = (
            ('enterprise', 'Can ALL enterprise'),
        )
        # no duplicate name, no duplicate tax_id
        unique_together = ('name', 'tax_id',)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if normalize('NFKD', u'%s' % self.name).encode('ascii', 'ignore').lower() in list(
                normalize('NFKD', u'%s' % c['name']).encode('ascii', 'ignore').lower() for c in Enterprise.objects.values('name').exclude(pk=self.pk)
        ):
            raise Exception(_(u'%(model_name)s with this %(field_label)s already exists.') % {
                'model_name': _('Enterprise'),
                'field_label': capfirst(_(u'name')),
            })
        if Enterprise.objects.exclude(pk=self.pk).filter(tax_id=self.tax_id).count() > 0:
            raise Exception(_(u'%(model_name)s with this %(field_label)s already exists.') % {
                'model_name': _('Enterprise'),
                'field_label': capfirst(_(u'Tax id')),
            })
        super(Enterprise, self).save(*args, **kwargs)


class Headquar(models.Model):

    """
    Tabla que contiene las sedes de las empresas, asociadas a una Asociación
    Un Headquar o sede o sucursal, es la unidad principal del sistema
    Los accesos del sistema serán entregados a un Headquarters
    """
    name = models.CharField(capfirst(_('name')), max_length=50)

    phone = models.CharField(_('Phone'), max_length=50, null=True, blank=True)

    address = models.TextField(_('Address'), null=True, blank=True)
    is_main = models.BooleanField(_('Main'), default=False)
    is_active = models.BooleanField(capfirst(_('active')), default=True)
    is_actived = models.BooleanField(_('Actived'), default=False)

    created_at = models.DateTimeField(_('Created at'), auto_now_add=True)
    updated_at = models.DateTimeField(_('Updated at'), auto_now=True)

    # locality = models.ForeignKey(Locality, verbose_name=_('Locality'),
    #	null=True, blank=True)
    association = models.ForeignKey(
        Association, verbose_name=_('Association'), null=True, blank=True)
    enterprise = models.ForeignKey(Enterprise, verbose_name=_('Enterprise'))

    class Meta:
        verbose_name = _('Headquar')
        verbose_name_plural = _('Headquars')
        permissions = (
            ('headquar', 'Can ALL headquar(sedes)'),
        )
        # no duplicate name by enterprise
        unique_together = (('name', 'enterprise'),)

    def __str__(self):
        return '%s %s (%s)' % (self.name, self.enterprise, self.association)

    def save(self, *args, **kwargs):
        if normalize('NFKD', u'%s' % self.name).encode('ascii', 'ignore').lower() in list(
                normalize('NFKD', u'%s' % c['name']).encode('ascii', 'ignore').lower() for c in Headquar.objects.values('name').exclude(pk=self.pk).filter(enterprise=self.enterprise)
        ):
            raise Exception(_(u'%(model_name)s with this %(field_label)s already exists.') % {
                'model_name': _('Headquar'),
                'field_label': capfirst(_(u'name')),
            })
        super(Headquar, self).save(*args, **kwargs)

backengo/accounts/models.py
from django.db import models

# Create your models here.

apps/accounts/templates/accounts/base_authenticated.html
{% extends "mod_backend/base.html" %}
{% load i18n staticfiles %}

{% block title %} {{ title }} | {{ site_title|default:_('Backend site admin') }} {% endblock title %}

{% block extrastyle %}
<link href="{% static 'jasny-bootstrap/css/jasny-bootstrap.css' %}" rel="stylesheet">

<link href="{% static 'custom/css/base.css' %}" rel="stylesheet">
<link href="{% static 'custom/css/style.css' %}" rel="stylesheet">
<link href="{% static 'bootstrap-fileinput/css/fileinput.css' %}" rel="stylesheet">
<link href="{% static 'custom/css/navbar-fixed-top.css' %}" rel="stylesheet">

{% endblock extrastyle%}

{% block header %}


{% include "accounts/partials/header.html" %}
{% endblock header %}


{% block rootcontainer %}
<div id="shell-load">
  <div class="breadcrumbs">
    {% block breadcrumbs %}

    {% endblock breadcrumbs %}
  </div>
  <div id="shell-content" class="container-fluid" >

    <div class="container shell-view">

      

      <div class="page-header">
        <h3>{% block content_title %}{% endblock content_title %}</h3>
      </div>
      {% block messages %}
      {% load notify %}
      {% get_notify request %}
      {% endblock messages %}

      {% block content %}{% endblock content %}
      {% block sidebar %}{% endblock sidebar %}

      
    </div>
  </div>
</div> <!-- /dw-shell-load -->
{% endblock rootcontainer %}


{% block footer %}
{% include "mod_backend/partials/footer.html" %}
{% endblock footer %}

<div id="loading-content" class="alpha60"></div>
<div id="spinner" class="preview corner-all shadow-dark"></div>

{% block extrajs %}
<!--
<script src="{% static 'jquery/jquery.spinx.js' %}"></script>
-->
<script src="{% static 'jasny-bootstrap/js/jasny-bootstrap.js' %}"></script>

<script src="{% static 'custom/js/jquery.kumbiaphp.js' %}"></script>
<script src="{% static 'custom/js/jquery.kgrid.js' %}"></script>
<!--
<script src="{% static 'custom/js/jquery.kloadx.js' %}"></script>
-->
<script src="{% static 'custom/js/backend.js' %}"></script>
<script src="{% static 'custom/js/validador.js' %}"></script>
<script src="{% static 'custom/js/jquery.keyfilter.js' %}"></script>
<script src="{% static 'bootstrap-fileinput/js/fileinput.js' %}"></script>
{% endblock extrajs %}

apps/accounts/templates/accounts/enterpriseassociation_form.html
{% extends "mod_backend/base_mod_backend.html" %}
<!--
@copyright   Copyright (c) 2014 Submit Consulting
@author      Angel Sullon (@asullom)
@package     account

Descripcion: Registra usuarios
-->

{% load i18n crispy_forms_tags notify %}

{% block rootcontainer %}

<div id="shell-load">
  <div id="shell-content" class="container-fluid" >
    <div class="container shell-view">


    <div class="page-header">
        <h3>{% trans 'Register' %}</h3>
        <p>{% blocktrans %}Add new association and new enterprise.
        To join an existing association, ask the administrator the association.{% endblocktrans %}</p>
    </div>
    {% get_notify request %}

    {% crispy form %}

</div>
</div>
</div> <!-- /dw-shell-load -->
{% endblock %}


{% block extrajs %}
{{ block.super }}

<script type="text/javascript">
$('#id_logo').fileinput({
	showUpload: false,
	showRemove: false,
	initialCaption: '{{ form.logo.value }}',
	initialPreview: ['<img src="{{ MEDIA_URL }}{{ form.logo.value }}">',],
	browseClass: 'btn btn-warning',
	browseLabel: '<span class="hidden-xs">{% trans "Pick image" %}</span>',
	browseIcon: '<i class="btn-icon-only glyphicon glyphicon-picture"></i>',
});

$('#form').on("submit", f=function() {
            if (confirm("¿Está seguro enviar esta información?")==true)
            {
                return true;
            }
            return false;
        });

</script>
{% endblock extrajs %}

apps/accounts/templates/accounts/index.html
{% extends "accounts/base_authenticated.html" %}
<!--
@copyright   Copyright (c) 2014 Submit Consulting
@author      Angel Sullon (@asullom)
@package     space

Descripcion: Lista solutions
-->
{% load i18n app_security %}
{% load l10n humanize %}

{% block breadcrumbs %}
<a href="{% url 'home:index' %}">{% trans 'Home' %}</a>
&rsaquo; {{ title }}
{% endblock breadcrumbs %}

{% block content_title %}
{{ opts|capfirst }} | <small>{{ title }}</small>
{% endblock content_title %}

{% block content %}
<script type="text/javascript">
$(function() {
    $('table').kgrid({
        form_data : ['{{f}}', '{{q}}'],
        form_to   : '/accounts/?f={{f}}&q={{q}}',
        order_attr: 'class=""',
        order_to  : '/accounts/?f={{f}}&q={{q}}',
    });
});
</script>



<div class="btn-toolbar btn-toolbar-top">
    <div class="row">
        <div class="btn-actions">
            {% if user.is_superuser %}
            <a href="/mod_backend/dashboard/" class="btn btn-primary text-bold" title="{% trans 'Go' %} {% trans 'Admin' %}"><i class="fa fa-key"></i> <span class="hidden-xs"> {% trans 'Go'  %} {% trans 'Admin'  %}</span></a>
            {% endif %}
            <a href="/accounts/add_enterprise/" class="btn btn-warning text-bold" title="{% trans 'Add' %} {% trans 'Solution' %}"><i class="fa fa-plus"></i> <span class="hidden-xs"> {% trans 'Add'  %} {% trans 'Enterprise'  %}</span></a>

        </div>
    </div>
</div>
<div class="container-overflow">
    <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
        <thead>
            <tr>
                <th>#</th>
                <th class="col-hidden" data-search="association__name" data-order="association__name">{% trans 'Association' %}</th>
                <th class="col-hidden" data-search="enterprise__name" data-order="enterprise__name">{% trans 'Enterprise' %}</th>
                <th class="col-hidden">{% trans 'Sede' %}</th>
                <th class="col-hidden">{% trans 'Profile'|capfirst %}</th>
                <th class="col-blocked text-center">{% trans 'Module' %}</th>
            </tr>
        </thead>
        <tbody>
            {% for d in object_list %}
            <tr class="{{ d.headquar.is_active|yesno:',danger' }}">
                <td>{% if is_paginated %}
                    {{ page_obj.start_index|add:forloop.counter0 }}
                    {% else %}
                    {{ forloop.counter }}
                    {% endif %}
                </td>
                <td>{{ d.association.name }}
                    <span class="label label-success">{{ d.association.is_active|yesno:',off' }}</span>
                </td>
                <td>
                	{{ d.enterprise.name }}
                    <span class="label label-success">{{ d.enterprise.is_active|yesno:',off' }}</span>
                </td>
                <td>
                	{{ d.headquar.name }}
                    <span class="label label-success">{{ d.headquar.is_active|yesno:',off' }}</span>
                </td>
                <td>{{ d.groups|join:', ' }} </td>
                <td class="text-center">
                	{% for d2 in d.modules %}
                    <a href="/accounts/load_access/{{ d.headquar.id}}/{{ d2.id }}" class="btn btn-info btn-sm text-bold" title="{% trans "Elegir." %}" rel="tooltip"> {{ d2.name }} </a>

                    {% endfor %}

                </td>
            </tr>
            {% endfor %}
        </tbody>

    </table>
</div>
<div  class="row" >
    {% if is_paginated %}
    {% load paginator %}
    {% paginator %}
    {% else %}
    <div class="col-md-12" >
        <ul class="breadcrumbpag" >
            {{ object_list.count }} {% ifequal object_list.count 1 %}{{ opts.verbose_name|capfirst }}{% else %}{{ opts.verbose_name_plural|capfirst }}{% endifequal %}
        </ul>
    </div>
    {% endif %}
</div>

{% endblock content %}