apps/clinica/urls.py
from django.conf.urls import url


from .views.atencionviews import AtencionHistoriaListView, AtencionListView, AtencionCreateView, AtencionTerminadaView
from .views.colamedicaviews import ColaMedicaListView,MainCreateView, ColaMedicaDeleteView, ColasMedicasListView, BuscarCliente
from .views.vacunacionviews import  get_drugs, BuscarProducto
from .views.consulta_diagnostico import  get_diagnosticos
from .views.tratamientos import  get_tratamientos
from .views.consulta_pruebas_auxiliares import  get_pruebas_auxiliares
from .views.historiaviews import HistoriasListView, HistoriaFichaListView,  HistoriaMascotaDetailView, HistoriaMascotaCreateView
from .views.mascotaviews import MascotaListView, MascotaCreateView, MascotaPerfilView, MascotaHistoriaListView, MascotaUpdateView, MascotaUpdateActiveView
from .views.cliente import ClienteListView, ClienteCreateView, ClienteUpdateView, ClienteDeleteView, PostClienteAjax
from .views.cunsulta import ConsultaCreateView, ConsultaUpdateView,  ConsultaDeleteView
from .views.notas import NotasCreateView, upload, upload_delete
from .views.vacunacion import VacunacionCreateView, PostVacunacionAjax
from .views.colamedicaviews import MainCreateView,VentasView
urlpatterns = [
    url(r'^api/get_drugs/', get_drugs, name='get_drugs'),
    url(r'^api/diagnostico/', get_diagnosticos, name='get_diagnosticos'),
    url(r'^api/pruebas_auxiliares/', get_pruebas_auxiliares, name='get_pruebas_auxiliares'),
    url(r'^api/tratamientos/', get_tratamientos, name='get_tratamientos'),

    #BUSQUEDAS-URLS

    url(r'^producto/search/',
        BuscarProducto, name='search_producto_recepcion'),
    url(r'^cliente/search/',BuscarCliente, name='search_cliente'),



#Atencion Medica
    url(r'^atenciones/listar/(?P<mascota_pk>[^/]+)/(?P<colamedica_pk>[^/]+)$', AtencionListView.as_view(), name="historia_list"),
    url(r'^atenciones/historia/(?P<mascota_pk>[^/]+)/(?P<colamedica_pk>[^/]+)$', AtencionHistoriaListView.as_view(), name="atencion_historia_list"),
    url(r'^atenciones/crear/(?P<mascota_pk>[^/]+)/(?P<colamedica_pk>[^/]+)/$', AtencionCreateView.as_view(), name="atenciones_add"),
    url(r'^atencion/terminada/(?P<state>[\w\d\-]+)/(?P<pk>.*)/$',
        AtencionTerminadaView.as_view(), name='atencion_satate'),

#Consultas
    url(r'^atencion/consulta/(?P<mascota_pk>[^/]+)/(?P<colamedica_pk>[^/]+)$', ConsultaCreateView.as_view(), name='consulta_add'),
    url(r'^atencion/consulta/editar/(?P<mascota_pk>[^/]+)/(?P<colamedica_pk>[^/]+)/(?P<atencion_pk>[^/]+)/(?P<pk>.*)/$', ConsultaUpdateView.as_view(), name='consulta_update'),
    url(r'^atencion/consulta/eliminar/(?P<mascota_pk>[^/]+)/(?P<colamedica_pk>[^/]+)/(?P<pk>.*)/$', ConsultaDeleteView.as_view(), name="consulta_delete"),

    #Notas
    url(r'^atencion/notas/(?P<mascota_pk>[^/]+)/(?P<colamedica_pk>[^/]+)/(?P<atencion_pk>[^/]+)/$', NotasCreateView.as_view(), name='nota_add'),

    #Archivos

    #Vacunacion
    url(r'^atencion/vacunacion/(?P<mascota_pk>[^/]+)/(?P<colamedica_pk>[^/]+)/$', VacunacionCreateView.as_view(), name='vacuna_add'),
    url(r'^atencion/vacunacion/crear-ajax/$', PostVacunacionAjax, name="post_vacunacion_ajax"),

    #Cola Medica
    url(r'^colamedica/listar/$', ColaMedicaListView.as_view(), name="listar_medica"),
    url(r'^colamedica/lista/$', ColasMedicasListView.as_view(), name="lista_medica"),

    url(r'^colamedica/crear/$', MainCreateView.as_view(), name="crear_medica"),
    url(r'^ventas/$', VentasView.as_view(), name="crear_venta"),
    url(r'^colamedica/eliminar/(?P<pk>.*)/$', ColaMedicaDeleteView.as_view(), name="eliminar_medica"),

    #url(r'^colamedica/detail/(?P<pk>.*)/$', AtencionMedicaView.as_view(), name='colamedica_detail'),



    # Historia
    url(r'^historia/listar/$', HistoriasListView.as_view(), name="listar_historia"),
    url(r'^historia/ficha/(?P<mascota_pk>[^/]+)$', HistoriaFichaListView.as_view(), name="ver_ficha_clinica"),
    url(r'^historia/crear/(?P<cliente_pk>[^/]+)/(?P<mascota_pk>[^/]+)$',
        HistoriaMascotaCreateView.as_view(), name='crear_historia'),
    url(r'^historia/detail/(?P<pk>.*)/$',
        HistoriaMascotaDetailView.as_view(), name='historia_detail'),

    # Mascota
    url(r'^mascota/listar/(?P<cliente_pk>[^/]+)$',
        MascotaListView.as_view(), name="mascota_list"),
    url(r'^mascota/crear/(?P<cliente_pk>[^/]+)$',
        MascotaCreateView.as_view(), name="mascota_add"),
    url(r'^mascota/actualizar/(?P<pk>.*)/$',
        MascotaUpdateView.as_view(), name="actualizar_mascota"),
    url(r'^mascota/state/(?P<state>[\w\d\-]+)/(?P<pk>.*)/$',
        MascotaUpdateActiveView.as_view(), name='mascota-state'),
    url(r'^mascota/perfil/(?P<pk>.*)/$', MascotaPerfilView.as_view(), name="mascota_perfil_list"),
    url(r'^mascota/historia/(?P<mascota_pk>[^/]+)/$', MascotaHistoriaListView.as_view(), name="historia_list"),
    # ===================CLIENTE==========================
    url(r'^cliente/listar/$', ClienteListView.as_view(), name="cliente_list"),
    url(r'^cliente/crear/$', ClienteCreateView.as_view(), name="cliente_add"),
    url(r'^cliente/actualizar/(?P<pk>.*)/$',
        ClienteUpdateView.as_view(), name="cliente_upd"),
    url(r'^cliente/eliminar/(?P<pk>.*)/$',
        ClienteDeleteView.as_view(), name="cliente_del"),
    url(r'^cliente/crear/ajax$', PostClienteAjax, name="post_cliente_ajax"),
]

config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django import views as django_views

from apps.clinica.views.notas import upload, upload_delete

from apps.clivet.views.main import  MainView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/', django_views.i18n.javascript_catalog),
    # =============================================================
    #                           backengo
    # =============================================================
    url(r'^mod_backend/', include('apps.mod_backend.urls', namespace='mod_backend')),
    url(r'^space/', include('apps.space.urls', namespace='space')),
    url(r'^sad/', include('apps.sad.urls', namespace='sad')),
    url(r'^accounts/', include('apps.accounts.urls')),
    # =============================================================
    #                           clivet
    # =============================================================


    url( r'upload/', upload, name = 'jfu_upload' ),
    url( r'^delete/(?P<pk>\d+)$', upload_delete, name = 'jfu_delete' ),

    # url(r'^about/$', AboutView.as_view()),
    url(r'^$', MainView.as_view(), name='dashboard'),

    url(r'^', include('apps.clivet.urls', namespace='clivet')),
    url(r'^clinica/', include('apps.clinica.urls', namespace='clinica')),
    url(r'^ventas/', include('apps.ventas.urls', namespace='ventas')),
    url(r'^configuracion/', include('apps.configuracion.urls', namespace='configuracion')),
    url(r'^compras/', include('apps.compras.urls', namespace='compras')),
    url(r'^citas/', include('apps.citas.urls', namespace='citas')),
    url(r'^acopios/', include('apps.acopios.urls', namespace='acopios')),
    # TODO: Poner en la aplicacion que se usa
    url(r'^chaining/', include('smart_selects.urls')),
]

urlpatterns = urlpatterns + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

apps/clinica/forms/atenciones.py
#encoding: utf-8
from django import forms

from django.utils.translation import ugettext_lazy as _
from django.utils.text import capfirst, get_text_list
from crispy_forms.helper import FormHelper, Layout
from crispy_forms.layout import Field, Div, Row, HTML
from crispy_forms.bootstrap import FormActions, TabHolder, Tab, InlineRadios, InlineCheckboxes

from backengo.utils.forms import smtSave, btnCancel, btnReset

from django.utils.timezone import get_current_timezone
from datetime import datetime

from ..models.atenciones import Atenciones, ArchivosAdjuntos

class AtencionesForm(forms.ModelForm):
    """Tipo Documeto Form."""
    class Meta:
        """Meta."""
        model = Atenciones
        exclude = ('colamedica',)
        fields = []

apps/clinica/forms/cliente.py
u"""Módulo Cliente Form."""

from django import forms
from ..models.cliente import Cliente
from apps.params.models import IDENTITY_TYPE_CHOICES
from django.utils.translation import ugettext_lazy as _
from crispy_forms.layout import Field, Div, Row, HTML
from crispy_forms.bootstrap import FormActions, TabHolder, Tab
from crispy_forms.helper import FormHelper, Layout
from backengo.utils.forms import smtSave, btnCancel, btnReset
from django.utils.text import capfirst, get_text_list


class ClienteForm(forms.ModelForm):
    u"""Cliente Form."""
    nombre = forms.CharField(max_length=100)
    apellidos = forms.CharField(max_length=100)
    numero = forms.IntegerField(required=False)
    tipo_documento = forms.ChoiceField(choices=IDENTITY_TYPE_CHOICES)
    fecha_de_nacimiento = forms.DateField(
        widget=forms.DateInput(attrs={'class': 'datepicker', }),
        required=False)
    # apellido = forms.CharField(max_length=100,widget=forms.Textarea)
    # sender = forms.EmailField()
    # cc_myself = forms.BooleanField(required=False)
    # producto = forms.ModelChoiceField(
    #     queryset=Producto.objects.all(),
    #     required=False, label="", help_text="")
    # data_venta = forms.CharField(
    #     required=False, widget=forms.TextInput(attrs={'type': 'hidden'}))
    #  hoice_field = forms.ChoiceField(widget=forms.RadioSelect,
    #                                 choices=CHOICES)

    class Meta:
        """Meta."""
        model = Cliente
        exclude = ('persona',)
        fields = ('direccion', 'ciudad', 'email', 'telefono')

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        self.object = kwargs.pop('object', None)
        super(ClienteForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Div(Field('nombre',  placeholder='Ingrese un nombre',
                          css_class='input-required'),
                    css_class='col-md-3'),
                Div(Field('apellidos', placeholder='Ingrese sus apellidos'),
                    css_class='col-md-4'),
                Div(Field('tipo_documento',), css_class='col-md-2'),
                Div(Field('numero', placeholder='Ingrese un número'),
                    css_class='col-md-3'),
            ),
            Row(
                Div(Field('fecha_de_nacimiento', placeholder='YYYY-MM-DD'),
                    css_class='col-md-2'),
                Div(Field('ciudad', placeholder='Ingrese el nombre'),
                    css_class='col-md-2'),
                Div(Field('direccion', placeholder='Ingrese una dirección'),
                    css_class='col-md-3'),
                Div(Field('email', placeholder='example@gmail.com'),
                    css_class='col-md-3'),
                Div(Field('telefono', placeholder='Ingrese el número'),
                    css_class='col-md-2'),
            ),
            Div(Row(
                FormActions(
                    smtSave(),
                    btnCancel(),
                    btnReset(),
                ),
            ), css_class='modal-footer',),
        )

apps/clinica/forms/colamedicaform.py
#encoding: utf-8
from django import forms

from django.utils.translation import ugettext_lazy as _
from django.utils.text import capfirst, get_text_list
from crispy_forms.helper import FormHelper, Layout
from crispy_forms.layout import Field, Div, Row, HTML
from crispy_forms.bootstrap import FormActions, TabHolder, Tab, StrictButton
from backengo.utils.forms import smtSave, btnCancel, btnReset
from django.utils.timezone import get_current_timezone
from datetime import datetime
from ..models.colamedica import ColaMedica
from ..models.mascota import Mascota
from apps.clinica.models.cliente import Cliente
from apps.sad.models import User

class ColaMedicaForm(forms.ModelForm):
    """Tipo Documeto Form."""
    cliente = forms.ModelChoiceField(
            queryset=Cliente.objects.all(), required=False, )

    mascotas = forms.ModelChoiceField(
            queryset=Mascota.objects.all(), required=False, )
    class Meta:
        """Meta."""
        model = ColaMedica
        exclude = ()
        fields = ['fuente_atencion','mascota','descripcion','medico',]

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        self.object = kwargs.pop('object', None)

        super(ColaMedicaForm, self).__init__(*args, **kwargs)

        self.fields['descripcion'] = forms.CharField(
            label=capfirst(_(u'Descripcion:')), required=True,
            help_text=u'<small class="help-error"></small> %s' % _(
                u' '),
        )
        self.fields['medico'] = forms.ModelChoiceField(
                    queryset=User.objects.filter(groups=10), required=False, )
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_class = 'js-validate'
        self.helper.layout = Layout(
            Row(
                Div(
                    Field('mascota',  css_class='input-required', readonly=True),
                        css_class="col-md-4"),
                Div(
                    Field('medico', css_class='input-required'),
                        css_class="col-md-4"),
                Div(
                    Field('fuente_atencion', placeholder="Introdusca el color", css_class='input-required'),
                        css_class="col-md-4"),
                Div(
                    Field('descripcion', ),
                        css_class="col-md-12"),
            ),
            Row(
                Div(
                    FormActions(
                        smtSave(),
                    ),
                css_class="col-md-12 btn-controls"),
            ),
        )

apps/clinica/forms/notas.py
u"""Módulo Notas Form."""
from django import forms
from apps.params.models import IDENTITY_TYPE_CHOICES
from django.utils.translation import ugettext_lazy as _
from crispy_forms.layout import Field, Div, Row, HTML
from crispy_forms.bootstrap import FormActions, TabHolder, Tab
from crispy_forms.helper import FormHelper, Layout
from backengo.utils.forms import smtSave, btnCancel, btnReset
from django.utils.text import capfirst, get_text_list

from ..models.nota import Notas

class NotasForm(forms.ModelForm):
    u"""Notas Form."""

    class Meta:
        """Meta."""
        model = Notas
        exclude = ('atenciones',)
        fields = ('descripcion',)

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        self.object = kwargs.pop('object', None)
        super(NotasForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Div(Field('descripcion', placeholder='Ingrese un la nota'),
                    css_class='col-md-12'),
            ),

            Div(Row(
                FormActions(
                    smtSave(),
                    btnCancel(),
                    btnReset(),
                ),
            ), css_class='modal-footer',),
        )

apps/clinica/forms/vacunacion.py
u"""Módulo Vacuna Form."""
from django import forms
from apps.params.models import IDENTITY_TYPE_CHOICES
from django.utils.translation import ugettext_lazy as _
from crispy_forms.layout import Field, Div, Row, HTML
from crispy_forms.bootstrap import FormActions, TabHolder, Tab
from crispy_forms.helper import FormHelper, Layout
from backengo.utils.forms import smtSave, btnCancel, btnReset
from django.utils.text import capfirst, get_text_list

from ..models.vacunacion import Vacunacion

class VacunacionForm(forms.ModelForm):
    u"""Vacuna Form."""

    class Meta:
        """Meta."""
        model = Vacunacion
        exclude = ('atenciones',)
        fields = ('motivo','vacuna','observacion',)

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        self.object = kwargs.pop('object', None)
        super(VacunacionForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Div(Field('motivo', placeholder='Ingrese el motivo de vacunación'),
                    css_class='col-md-12'),
                Div(Field('vacuna',),
                    css_class='col-md-12'),
                Div(Field('observacion', placeholder='Ingrese un la nota'),
                    css_class='col-md-12'),
            ),

            Div(Row(
                FormActions(
                    smtSave(),
                    btnCancel(),
                    btnReset(),
                ),
            ),),
        )

apps/clinica/templates/clinica/cliente/form.html
{% extends "main/dashboard.html" %}
{% load l10n i18n %}
{% load crispy_forms_tags %}
{% block breadcrumbs_item %}
    <li><a href="{% url 'clinica:cliente_list' %}">{{ opts.verbose_name_plural|capfirst }}</a></li>
    <li class="active">{{ title }}</li>
{% endblock breadcrumbs_item %}

{% block page_title %}
    <i class="fa fa-user"></i> {{ title }}
{% endblock page_title %}
{% block page_content %}

    <form action="" method="post">
        {% csrf_token %}
        {% crispy form %}
    </form>

{% endblock %}

{% block extrajs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#id_fecha_de_nacimiento').datetimepicker({
            format: 'YYYY-MM-DD',
            //format: 'YYYY-MM-DD hh:mm:ss', //pata datatimes
            language: 'es',
            pickTime: false,
            //showMeridian: true,
            autoclose: true,
            todayHighlight: true,
        });

    </script>
{% endblock extrajs %}

apps/clinica/templates/clinica/cliente/index.html
{% extends "main/dashboard.html" %} {% load i18n app_security %} {% load l10n humanize %}
{% block style %}
    <style media="screen">
        .detail-row {
            display: none;
        }

        .open.show_row {
            display: table-row;
        }
    </style>
{% endblock style %}
{% block breadcrumbs_item %}
    <li class="active">{{ title }}</li>
{% endblock breadcrumbs_item %}

{% block page_title %}
    <i class="fa fa-users"></i> Lista de {{ opts.verbose_name_plural }}
    <small>
        <i class="ace-icon fa fa-angle-double-right"></i>
        {{ title }}
    </small>
{% endblock page_title %}
{% block page_content %}
    <script type="text/javascript">
        $(function () {
            $('table').kgrid({
                form_data: ['{{f}}', '{{q}}'],
                form_to: '{% url 'clinica:cliente_list' %}?f={{f}}&q={{q}}',
                order_attr: 'class=""',
                order_to: '{% url 'clinica:cliente_list' %}?f={{f}}&q={{q}}',
            });
        });
    </script>
    <div class="btn-toolbar btn-toolbar-top">
        <div class="row">
            <div class="btn-actions col-md-9">
                <a href="{% url 'clinica:cliente_add' %}" class="btn btn-primary text-bold" title="Agregar Cliente">
                    <i class="fa fa-plus"></i>
                    <span class="hidden-xs"> Agregar</span>
                </a>
            </div>
        </div>
    </div>
    <div class="container-overflow">
        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
            <tr>
                <th>#</th>
                <th class="detail-col">Detalle</th>
                <th class="col-hidden" data-order="persona__last_name" data-search="persona__first_name">Apellidos y
                    Nombres
                </th>
                <th class="col-hidden">E-mail</th>
                <th class="col-hidden">
                    <i class="ace-icon fa fa-clock-o bigger-110 hidden-480"></i>
                    Update
                </th>
                <th class="col-hidden col-blocked text-center ">N° Producto</th>
                <th class="text-center">Add Producto</th>
                <th class="btn-actions col-blocked text-center">Acción</th>
            </tr>
            </thead>
            <tbody>
            {% for d in object_list %}
                <tr>
                    <td>{% if is_paginated %} {{ page_obj.start_index|add:forloop.counter0 }} {% else %}
                        {{ forloop.counter }} {% endif %}
                    </td>
                    <td class="center">
                        <div class="action-buttons">
                            <a href="#" class="green bigger-140 show-details-btn" title="Show Details">
                                <i class="ace-icon fa fa-angle-double-down"></i>
                                <span class="sr-only">Details</span>
                            </a>
                        </div>
                    </td>
                    <td>{{ d.persona.last_name }} {{ d.persona.first_name }} </td>
                    <td><a>{{ d.email }}</a></td>
                    <td>{{ d.updated }}</td>
                    {% if d.mascotas.count %}
                        <td><span class="badge badge-success">{{ d.mascotas.count }}</span></td>
                    {% else %}
                        <td><span class="badge badge-danger">{{ d.mascotas.count }}</span></td>
                    {% endif %}


                    <td>
                       <a href="#">
          <span class="glyphicon glyphicon-plus"></span>
        </a>
                    </td>
                    <td class="text-center">
                        <a href="{% url 'clinica:cliente_upd' d.pk %}" class="btn btn-info btn-sm text-bold"
                           title="Cambiar Cliente" rel="tooltip">
                            <i class="btn-icon-only fa fa-edit"></i>
                        </a>
                        <a href="{% url 'clinica:cliente_del' d.pk|key:'doc_del' %}"
                           class="btn btn-danger btn-sm js-confirm text-bold" msg-title="Eliminar Cliente?." msg="Esta Seguro
                       <br/>Recuerde esta operación no puede revertirse" title="Eliminar Cliente" rel="tooltip">
                            <i class="btn-icon-only fa fa-trash-o"></i>
                        </a>
                    </td>
                </tr>
                <tr class="detail-row">
                    <td colspan="8">
                        <div class="table-detail">
                            <div class="row">
                                <div class="col-xs-12 col-sm-2">
                                    <div class="text-center">
                                        <img height="150" class="thumbnail inline no-margin-bottom"
                                             alt="Domain Owner's Avatar" src="{{ MEDIA_URL }}{{ d.persona.photo }}">
                                        <br>
                                        <div class="width-80 label label-info label-xlg arrowed-in arrowed-in-right">
                                            <div class="inline position-relative">
                                                <a class="user-title-label" href="#">
                                                    <i class="ace-icon fa fa-circle light-green"></i>
                                                    &nbsp;
                                                    <span class="white">{{ d.persona.first_name }}</span>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-xs-12 col-sm-7">
                                    <div class="space visible-xs"></div>

                                    <div class="profile-user-info profile-user-info-striped">
                                        <div class="profile-info-row">
                                            <div class="profile-info-name"> Cliente</div>

                                            <div class="profile-info-value">
                                                <span>{{ d.persona.first_name }} {{ d.persona.last_name }} </span>
                                            </div>
                                        </div>
                                        <div class="profile-info-row">
                                            <div class="profile-info-name">{{ d.persona.identity_type }} </div>
                                            <div class="profile-info-value">
                                                <span>{{ d.persona.identity_num }} </span>
                                            </div>
                                        </div>

                                        <div class="profile-info-row">
                                            <div class="profile-info-name"> Ciudad</div>
                                            <div class="profile-info-value">
                                                <i class="fa fa-map-marker light-orange bigger-110"></i>
                                                <span>{{ d.ciudad }}</span>
                                            </div>
                                        </div>
                                        <div class="profile-info-row">
                                            <div class="profile-info-name"> Direccion</div>
                                            <div class="profile-info-value">
                                                <i class="fa fa-map-marker light-orange bigger-110"></i>
                                                <span>{{ d.direccion }}</span>
                                            </div>
                                        </div>
                                        <div class="profile-info-row">
                                            <div class="profile-info-name">F. Nacimiento</div>

                                            <div class="profile-info-value">
                                                <span>{{ d.persona.birth_date }}</span>
                                            </div>
                                        </div>
                                        <div class="profile-info-row">
                                            <div class="profile-info-name">Telefono</div>
                                            <div class="profile-info-value">
                                                <span>{{ d.telefono }}</span>
                                            </div>
                                        </div>
                                        <div class="profile-info-row">
                                            <div class="profile-info-name"> Registrado</div>

                                            <div class="profile-info-value">
                                                <span>{{ d.created }}</span>
                                            </div>
                                        </div>


                                        <div class="profile-info-row">
                                            <div class="profile-info-name"> Ventas</div>

                                            <div class="profile-info-value">
                                                <span>{{ d.venta_set.count }}</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-xs-12 col-sm-3">
                                    <div class="space visible-xs"></div>
                                    <h4 class="header blue lighter less-margin">Enviar Mensaje
                                        a {{ d.persona.first_name }}</h4>

                                    <div class="space-6"></div>

                                    <form>
                                        <fieldset>
                                            <textarea class="width-100" resize="none"
                                                      placeholder="Escriba aqui…"></textarea>
                                        </fieldset>

                                        <div class="hr hr-dotted"></div>

                                        <div class="clearfix">
                                            <label class="pull-left">
                                                <input type="checkbox" class="ace">
                                                <span class="lbl"> Email me a copy</span>
                                            </label>

                                            <button class="pull-right btn btn-sm btn-primary btn-white btn-round"
                                                    type="button">
                                                Enviar
                                                <i class="ace-icon fa fa-arrow-right icon-on-right bigger-110"></i>
                                            </button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>

            {% endfor %}

            </tbody>
        </table>
    </div>
    <div class="row">
        {% if is_paginated %} {% load paginator %} {% paginator %} {% else %}
            <div class="col-md-12">
                <ul class="breadcrumbpag">
                    {{ object_list.count }} {% ifequal object_list.count 1 %}{{ opts.verbose_name|capfirst }}{% else %}
                    {{ opts.verbose_name_plural|capfirst }}{% endifequal %}
                </ul>
            </div>
        {% endif %}
    </div>
{% endblock page_content %}
{% block extrajs %} {{ block.super }}
    <script type="text/javascript">
        $('.show-details-btn').on('click', function (e) {
            e.preventDefault();
            var dd = $('.show-details-btn i ').css('color');
            console.log("IMprimiedo:", dd);
            console.log("holaaaaaaa");
            $(this).closest('tr').next().toggleClass('open');
            $(this).find(ace.vars['.icon']).toggleClass('fa-angle-double-down').toggleClass('fa-angle-double-up');
            $('.detail-row').addClass('show_row');
        });
    </script>
{% endblock extrajs %}